server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # dev ??? update / prod ?????? none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
    upload-dir: E:/A5基于讯飞人工智能平台数智化教育应用软件开发/education-platform/uploads

iflytek:
  app-id: 48b28dad
  api-key: a3c9742fe3a8ca5f8ab0ae58c66a097a
  api-secret: YzgxYzQ3NGIzZTM5Y2JkOGUwZmJkZWFi
  model: "4.0Ultra" # 讯飞模型名称

